### PR TITLE
MNEMONIC-344: The error message is not correct for failing test case

### PR DESCRIPTION
**Pull request by weiho1122**

### CODE REVIEW

**Comment by weiho1122** [comment]
MNEMONIC-344: The error message is not correct for failing test case
--

**Comment by bigdata-memory** [comment]
Please rebase your PR again, Thanks!

**Comment by weiho1122** [comment]
rebase done, please approve

**Comment by bigdata-memory** [comment]
Hi @weiho1122 please merge commits from upstream and then apply your changes to PR, Thanks!

**Pull request merged**
