### PR TITLE
MNEMONIC-332: The Logo in docker page deprecated

### PR DESCRIPTION
**Pull request by jerryZh65**
Updated the logo in the docker's `README.md` to use the same in the roject's `README.md`

### CODE REVIEW

**Comment by jerryZh65** [comment]
@bigdata-memory updated the title of PR #57

**Comment by jerryZh65** [comment]
@bigdata-memory I have merged the commits from the master.

I did not pull the latest commits as I only modified the docker's `README` and I checked commits of this file and did not find the new commits since the time I pulled the code.

I'll pull the latest code when raising new PRs from now on.

**Comment by bigdata-memory** [comment]
Please use rebase instead of pull to keep the git log clean. the pull merge could be revoked by git reset using --hard option and then git fetch -a, finally use git rebase to rebase your code from Apache project repos.
Please [Visit this](http://mnemonic.incubator.apache.org/docs/submitchanges.html) for detailed steps, Thanks!

**Comment by jerryZh65** [comment]
Thanks for sharing the doc `[submit changes](http://mnemonic.incubator.apache.org/docs/submitchanges.html)`

**Pull request closed without merging**
